# Generated by Django 3.2.4 on 2021-12-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Model', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('JAN_Code', models.CharField(max_length=50)),
            ],
        ),
    ]
